import 'dart:convert';
import 'dart:io';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart';

import '../firebase_emulator/dev_machine_ip.dart';

/// A service for managing push notifications.
///
/// A key feature of this application is the ability to receive push notifications and display them to users when the
/// salt and/or battery levels of their Brine devices are low. This allows users to take actions such as refilling their
/// water softener with salt or replacing the batteries in their devices.
///
/// This service is responsible for managing the registration of devices for push notifications by leveraging the
/// functionality provided by the Firebase Cloud Messaging (FCM) SDK. Critically, this service is responsible for
/// managing the FCM tokens stored in the Firestore database for each user. These tokens are used to send push
/// notifications to the user's devices.
class PushNotificationsService {
  /// The Firebase Auth [User] object representing the current user.
  final User user;

  /// Creates an instance of the [PushNotificationsService] class with the specified [user].
  PushNotificationsService({required this.user});

  /// The host for the Firebase Functions base URL.
  static final String _cloudFunctionsHost = kDebugMode ? devMachineIP : ''; // TODO(Toglefritz): update prod host

  /// The base URL for all endpoints used by this service.
  static String baseUrl = kDebugMode
      ? 'http://$_cloudFunctionsHost:5001/brine-3b212/us-central1'
      : ''; // TODO(Toglefritz): update prod endpoint

  /// Sends the FCM token of the current device to the Firestore database.
  ///
  /// FCM tokens are used to send push notifications to devices. Each mobile device has a unique FCM token that is
  /// generated by the FCM SDK. This token is used to identify the device when sending push notifications.
  ///
  /// Because FCM tokens are unique per mobile device, a user might have more than one FCM token if they use more than
  /// one mobile device. Additionally, the FCM token for a device can change over time for semi-unpredictable reasons
  /// such as OS updates, app updates, or other factors. Last, if a user has denied the app permission to send push
  /// notifications, the FCM token will not be generated.
  Future<void> registerFcmToken() async {
    try {
      // Retrieve the FCM token for the current device
      final String? fcmToken = await FirebaseMessaging.instance.getToken();

      if (fcmToken == null) {
        debugPrint('FCM token is null. Push notifications might be disabled.');
        return;
      }

      // Get the authenticated user's Firebase ID token
      final String? idToken = await FirebaseAuth.instance.currentUser?.getIdToken();

      if (idToken == null) {
        throw Exception('User is not authenticated. Cannot register FCM token.');
      }

      // Define the backend endpoint URL
      const String endpoint = '/addFcmToken';

      // Make an authenticated HTTP POST request to register the FCM token
      final Response response = await post(
        Uri.parse(baseUrl + endpoint),
        headers: {
          'Authorization': 'Bearer $idToken',
          'Content-Type': 'application/json',
        },
        body: jsonEncode({'fcmToken': fcmToken}),
      );

      // Check the response status code
      if (response.statusCode == HttpStatus.ok) {
        debugPrint('Successfully registered FCM token: $fcmToken');
      } else {
        throw Exception('FCM token registration failed: ${response.reasonPhrase}');
      }
    } catch (e) {
      debugPrint('Failed to register FCM token with exception: $e');
      throw Exception('Failed to register FCM token with exception: $e');
    }
  }
}
