name: brine
description: Companion app for the Brine water softener monitor.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Creates Material color schemes based on a platform's implementation of dynamic color
  dynamic_color: ^1.5.4
  # Used to display SVG assets
  flutter_svg: ^1.1.6
  # Used to get Google Fonts font styles
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
