name: brine
description: Companion app for the Brine water softener monitor.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Used to access Firestore
  cloud_firestore: ^4.8.2
  # Used to call Firebase callable functions
  cloud_functions: ^4.3.1
  # Creates Material color schemes based on a platform's implementation of dynamic color
  dynamic_color: ^1.5.4
  # Used to display SVG assets
  flutter_svg: ^2.0.6
  # Provides additional icons beyond the Material icons
  font_awesome_flutter: ^10.3.0
  # Enables the use of Firebase services
  firebase_core: ^2.13.0
  # Firebase Auth services
  firebase_auth: ^4.6.1
  # Used to get Google Fonts font styles
  google_fonts: ^4.0.4
  # Allows authentication using a Google account
  google_sign_in: ^6.1.1
  # Automates setting the app icons
  flutter_launcher_icons: ^0.13.1
  # Provides loading widgets
  flutter_spinkit: ^5.2.0
  # Used to define localizable strings
  flutter_localizations:
    sdk: flutter
  # Used for internationalization
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/brine_round.png"
  remove_alpha_ios: true
  adaptive_icon_background: #ffffff
  adaptive_icon_foreground: "assets/icons/brine_round.png"
