name: brine
description: Companion app for the Brine water softener monitor.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Creates Material color schemes based on a platform's implementation of dynamic color
  dynamic_color: ^1.5.4
  # Used to display SVG assets
  flutter_svg: ^1.1.6
  # Used to get Google Fonts font styles
  google_fonts: ^3.0.1
  # Provides additional icons beyond the Material icons
  font_awesome_flutter: ^10.3.0
  # Enables the use of Firebase services
  firebase_core: ^2.4.0
  # Firebase Auth services
  firebase_auth: ^4.2.3
  # Allows authentication using a Google account
  google_sign_in: ^5.4.2
  # Used to access Firestore
  cloud_firestore: ^4.3.0
  # Used to call Firebase callable functions
  cloud_functions: ^4.1.1
  # Automates setting the app icons
  flutter_launcher_icons: ^0.11.0
  # Used to ensure only authorized clients access Firebase resources
  firebase_app_check: ^0.1.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/brine_round.png"
  remove_alpha_ios: true
  adaptive_icon_background: #ffffff
  adaptive_icon_foreground: "assets/icons/brine_round.png"
