/// Represents a pre-shared key (PSK) to be sent to the Brine device during provisioning.
///
/// A pre-shared key (PSK) is a secret key generated during the provisioning process to authenticate and secure
/// communication between the Brine device and the backend. The PSK is used by the Brine device to sign requests using
/// an HMAC, ensuring that only devices with valid keys can interact with the backend.
///
/// In the Brine system, the app handles the PSK ephemerally—meaning it does not store or retain the PSK beyond the
/// duration of the provisioning process. Once the key is securely transferred to the Brine device via Bluetooth, the
/// app discards it.
///
/// This design ensures that sensitive keys are not persistently stored on the mobile device, enhancing the overall
/// security of the system by limiting key exposure.
class PreSharedKey {
  /// The pre-shared key (PSK) value.
  final String value;

  /// Creates a [PreSharedKey] instance.
  PreSharedKey._(this.value);

  /// Creates a [PreSharedKey] instance from a JSON map.
  ///
  /// PSK values are generated by the Firebase backend. The app calls an API request to the backend to retrieve a PSK
  /// value, which is then used to create a [PreSharedKey] instance. The PSK value is returned in a JSON object using a
  /// format like,
  ///
  /// ```json
  /// {
  /// "psk":"7caf96e97207a08a4a90b9a845d7259703f255790f8384f812fe44c605e1d23b"
  /// }
  /// ```
  factory PreSharedKey.fromJson(Map<String, dynamic> json) {
    return PreSharedKey._(json['psk'] as String);
  }
}
