// Mocks generated by Mockito 5.4.6 from annotations in
// brine/test/screens/device_configuration/appliance_measurement/helpers/mock_ble_communication_service.dart. Do not
// manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:brine/services/ble/ble_communication_service.dart' as _i3;
import 'package:flutter_splendid_ble/central/models/ble_characteristic.dart' as _i2;
import 'package:flutter_splendid_ble/shared/models/ble_device.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint ignore_for_file: avoid_redundant_argument_values ignore_for_file:
// avoid_setters_without_getters ignore_for_file: comment_references ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package ignore_for_file: implementation_imports ignore_for_file:
// invalid_use_of_visible_for_testing_member ignore_for_file: must_be_immutable ignore_for_file:
// prefer_const_constructors ignore_for_file: unnecessary_parenthesis ignore_for_file: camel_case_types ignore_for_file:
// subtype_of_sealed_class ignore_for_file: invalid_use_of_internal_member

class _FakeBleCharacteristic_0 extends _i1.SmartFake implements _i2.BleCharacteristic {
  _FakeBleCharacteristic_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [BleCommunicationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleCommunicationService extends _i1.Mock implements _i3.BleCommunicationService {
  @override
  _i2.BleCharacteristic get characteristic =>
      (super.noSuchMethod(
            Invocation.getter(#characteristic),
            returnValue: _FakeBleCharacteristic_0(
              this,
              Invocation.getter(#characteristic),
            ),
            returnValueForMissingStub: _FakeBleCharacteristic_0(
              this,
              Invocation.getter(#characteristic),
            ),
          )
          as _i2.BleCharacteristic);

  @override
  void registerCallback(void Function(Map<String, dynamic>)? callback) => super.noSuchMethod(
    Invocation.method(#registerCallback, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterCallback(void Function(Map<String, dynamic>)? callback) => super.noSuchMethod(
    Invocation.method(#unregisterCallback, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> writeValue({required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#writeValue, [], {#value: value}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect(_i5.BleDevice? device) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [device]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
