// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Firebase options for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration for Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Er8QPJGPl5PZy-9unKz95YnGcK8_IH0',
    appId: '1:431909607108:android:f445d8bb684be5ed081b91',
    messagingSenderId: '431909607108',
    projectId: 'brine-3b212',
    databaseURL: 'https://brine-3b212-default-rtdb.firebaseio.com',
    storageBucket: 'brine-3b212.appspot.com',
  );

  /// Firebase options for iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Jp6ChQT_YiGZYcXIVbecMwZgzxMT3EM',
    appId: '1:431909607108:ios:b460491fabbdbbe7081b91',
    messagingSenderId: '431909607108',
    projectId: 'brine-3b212',
    databaseURL: 'https://brine-3b212-default-rtdb.firebaseio.com',
    storageBucket: 'brine-3b212.appspot.com',
    iosClientId: '431909607108-fm71ojb002kpajjshvbiq339al6425m3.apps.googleusercontent.com',
    iosBundleId: 'com.splendidendeavors.brine',
  );

  /// Firebase options for MacOS.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Jp6ChQT_YiGZYcXIVbecMwZgzxMT3EM',
    appId: '1:431909607108:ios:418bcfcdb8a0557c081b91',
    messagingSenderId: '431909607108',
    projectId: 'brine-3b212',
    databaseURL: 'https://brine-3b212-default-rtdb.firebaseio.com',
    storageBucket: 'brine-3b212.appspot.com',
    iosClientId: '431909607108-u6giq99kb5qbjp0g4radkkvsmt2b8b2j.apps.googleusercontent.com',
    iosBundleId: 'com.splendidendeavors.brineApp',
  );
}
