// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjGD4mVK8_rbOGn7u1-FMuUTLJN2EijBE',
    appId: '1:431909607108:web:7e8a0530cc1cd5a8081b91',
    messagingSenderId: '431909607108',
    projectId: 'brine-3b212',
    authDomain: 'brine-3b212.firebaseapp.com',
    databaseURL: 'https://brine-3b212-default-rtdb.firebaseio.com',
    storageBucket: 'brine-3b212.appspot.com',
    measurementId: 'G-G0FBWT7JL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Er8QPJGPl5PZy-9unKz95YnGcK8_IH0',
    appId: '1:431909607108:android:f445d8bb684be5ed081b91',
    messagingSenderId: '431909607108',
    projectId: 'brine-3b212',
    databaseURL: 'https://brine-3b212-default-rtdb.firebaseio.com',
    storageBucket: 'brine-3b212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Jp6ChQT_YiGZYcXIVbecMwZgzxMT3EM',
    appId: '1:431909607108:ios:b460491fabbdbbe7081b91',
    messagingSenderId: '431909607108',
    projectId: 'brine-3b212',
    databaseURL: 'https://brine-3b212-default-rtdb.firebaseio.com',
    storageBucket: 'brine-3b212.appspot.com',
    iosClientId: '431909607108-fm71ojb002kpajjshvbiq339al6425m3.apps.googleusercontent.com',
    iosBundleId: 'com.splendidendeavors.brine',
  );
}
