import 'package:flutter/material.dart';

import '../../../services/device_management/models/brine_device.dart';
import '../../../services/ble/ble_communication_service.dart';
import 'pre_shared_key_setup_controller.dart';

/// Requests a pre-shared key (PSK) from the Firebase backend and transfers the PSK to the Brine device.
///
/// This route is responsible for the following:
///
/// 1. Requesting a pre-shared key (PSK) from the Firebase backend.
/// 2. Transferring the PSK to the Brine device.
///
/// After the PSK is transferred to the Brine device, the app will navigate to the `WiFiSetupRoute`.
///
/// The pre-shared key is part of the security configuration for the Brine device. When it makes a request to the
/// cloud backend, the Brine device uses the PSK to create an HMAC signature that is sent with the request. This allows
/// the backend to verify that the request is coming from a legitimate Brine device.
///
/// To avoid compromising the PSK by including it in the Brine device firmware, the PSK is generated by the backend
/// and transferred to the Brine device during the device configuration process.
class PreSharedKeySetupRoute extends StatefulWidget {
  /// Creates an instance of [PreSharedKeySetupRoute].
  const PreSharedKeySetupRoute({
    required this.device,
    required this.bleCommunicationManager,
    super.key,
  });

  /// The [BrineDevice] that is the target of the device configuration process.
  final BrineDevice device;

  /// A [BleCommunicationService] instance that manages the communication between the app and the Brine device.
  final BleCommunicationService bleCommunicationManager;

  @override
  State<PreSharedKeySetupRoute> createState() => PreSharedKeySetupController();
}
