M48
; DRILL file {KiCad 9.0.0-rc3} date 2025-04-05T21:04:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-05T21:04:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0-rc3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X178.0Y-113.98
X187.0Y-113.98
T2
X125.304Y-109.252
X145.624Y-109.252
M30
