; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:sparkfun_esp32_iot_redboard]
platform = espressif32
board = sparkfun_esp32_iot_redboard
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.partitions = min_spiffs.csv
lib_deps = 
	sparkfun/SparkFun Qwiic Button and Qwiic Switch Library@^2.0.6
	sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor@^1.2.12
	adafruit/Adafruit_VL53L0X@^1.2.0
	bblanchon/ArduinoJson@^7.0.4
	sparkfun/SparkFun ATECCX08a Arduino Library@^1.3.1
	armmbed/mbedtls@^2.23.0
	sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library@^1.0.4
	fastled/FastLED@^3.6.0

; Preprocessdor directives
;  FLAVOR: Use 1 for development or 2 for production
;  DEBUG_MODE: Use 1 to enable debug output or zero to disable this output
build_flags = -I include -D FLAVOR=1 -D DEBUG_MODE=1 -DFIREBASE_EMULATOR_IP="\"192.168.86.39\"" -D GPIO_BUTTON_PIN=8

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.partitions = min_spiffs.csv
lib_deps = 
	sparkfun/SparkFun Qwiic Button and Qwiic Switch Library@^2.0.6
	sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor@^1.2.12
	adafruit/Adafruit_VL53L0X@^1.2.0
	bblanchon/ArduinoJson@^7.0.4
	sparkfun/SparkFun ATECCX08a Arduino Library@^1.3.1
	armmbed/mbedtls@^2.23.0
	sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library@^1.0.4
	fastled/FastLED@^3.6.0
build_flags = -I include -D FLAVOR=1 -D DEBUG_MODE=1 -DFIREBASE_EMULATOR_IP="\"192.168.86.39\"" -D WS2812B_LED -D WS2812B_DATA_PIN=9 -D GPIO_BUTTON_PIN=8 -D VL53L0X_SENSOR
