// Mocks generated by Mockito 5.4.6 from annotations
// in brine/test/screens/device_configuration/device_connection/helpers/mock_splendid_ble_central.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_splendid_ble/central/models/ble_connection_state.dart'
    as _i10;
import 'package:flutter_splendid_ble/central/models/ble_service.dart' as _i11;
import 'package:flutter_splendid_ble/central/models/connected_ble_device.dart'
    as _i5;
import 'package:flutter_splendid_ble/central/models/scan_filter.dart' as _i8;
import 'package:flutter_splendid_ble/central/models/scan_settings.dart' as _i9;
import 'package:flutter_splendid_ble/central/splendid_ble_central.dart' as _i2;
import 'package:flutter_splendid_ble/shared/models/ble_device.dart' as _i7;
import 'package:flutter_splendid_ble/shared/models/bluetooth_permission_status.dart'
    as _i6;
import 'package:flutter_splendid_ble/shared/models/bluetooth_status.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SplendidBleCentral].
///
/// See the documentation for Mockito's code generation for more information.
class MockSplendidBleCentral extends _i1.Mock
    implements _i2.SplendidBleCentral {
  @override
  _i3.Future<_i4.BluetoothStatus> checkBluetoothAdapterStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkBluetoothAdapterStatus, []),
            returnValue: _i3.Future<_i4.BluetoothStatus>.value(
              _i4.BluetoothStatus.enabled,
            ),
            returnValueForMissingStub: _i3.Future<_i4.BluetoothStatus>.value(
              _i4.BluetoothStatus.enabled,
            ),
          )
          as _i3.Future<_i4.BluetoothStatus>);

  @override
  _i3.Future<_i3.Stream<_i4.BluetoothStatus>> emitCurrentBluetoothStatus() =>
      (super.noSuchMethod(
            Invocation.method(#emitCurrentBluetoothStatus, []),
            returnValue: _i3.Future<_i3.Stream<_i4.BluetoothStatus>>.value(
              _i3.Stream<_i4.BluetoothStatus>.empty(),
            ),
            returnValueForMissingStub:
                _i3.Future<_i3.Stream<_i4.BluetoothStatus>>.value(
                  _i3.Stream<_i4.BluetoothStatus>.empty(),
                ),
          )
          as _i3.Future<_i3.Stream<_i4.BluetoothStatus>>);

  @override
  _i3.Future<List<_i5.ConnectedBleDevice>> getConnectedDevices(
    List<String>? serviceUUIDs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConnectedDevices, [serviceUUIDs]),
            returnValue: _i3.Future<List<_i5.ConnectedBleDevice>>.value(
              <_i5.ConnectedBleDevice>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i5.ConnectedBleDevice>>.value(
                  <_i5.ConnectedBleDevice>[],
                ),
          )
          as _i3.Future<List<_i5.ConnectedBleDevice>>);

  @override
  _i3.Future<_i6.BluetoothPermissionStatus> requestBluetoothPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestBluetoothPermissions, []),
            returnValue: _i3.Future<_i6.BluetoothPermissionStatus>.value(
              _i6.BluetoothPermissionStatus.granted,
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.BluetoothPermissionStatus>.value(
                  _i6.BluetoothPermissionStatus.granted,
                ),
          )
          as _i3.Future<_i6.BluetoothPermissionStatus>);

  @override
  _i3.Future<_i3.Stream<_i6.BluetoothPermissionStatus>>
  emitCurrentPermissionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#emitCurrentPermissionStatus, []),
            returnValue:
                _i3.Future<_i3.Stream<_i6.BluetoothPermissionStatus>>.value(
                  _i3.Stream<_i6.BluetoothPermissionStatus>.empty(),
                ),
            returnValueForMissingStub:
                _i3.Future<_i3.Stream<_i6.BluetoothPermissionStatus>>.value(
                  _i3.Stream<_i6.BluetoothPermissionStatus>.empty(),
                ),
          )
          as _i3.Future<_i3.Stream<_i6.BluetoothPermissionStatus>>);

  @override
  void stopScan() => super.noSuchMethod(
    Invocation.method(#stopScan, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i3.Stream<_i7.BleDevice>> startScan({
    List<_i8.ScanFilter>? filters,
    _i9.ScanSettings? settings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startScan, [], {
              #filters: filters,
              #settings: settings,
            }),
            returnValue: _i3.Future<_i3.Stream<_i7.BleDevice>>.value(
              _i3.Stream<_i7.BleDevice>.empty(),
            ),
            returnValueForMissingStub:
                _i3.Future<_i3.Stream<_i7.BleDevice>>.value(
                  _i3.Stream<_i7.BleDevice>.empty(),
                ),
          )
          as _i3.Future<_i3.Stream<_i7.BleDevice>>);

  @override
  _i3.Future<_i3.Stream<_i10.BleConnectionState>> connect({
    required String? deviceAddress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {#deviceAddress: deviceAddress}),
            returnValue: _i3.Future<_i3.Stream<_i10.BleConnectionState>>.value(
              _i3.Stream<_i10.BleConnectionState>.empty(),
            ),
            returnValueForMissingStub:
                _i3.Future<_i3.Stream<_i10.BleConnectionState>>.value(
                  _i3.Stream<_i10.BleConnectionState>.empty(),
                ),
          )
          as _i3.Future<_i3.Stream<_i10.BleConnectionState>>);

  @override
  _i3.Future<_i3.Stream<List<_i11.BleService>>> discoverServices(
    String? deviceAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#discoverServices, [deviceAddress]),
            returnValue: _i3.Future<_i3.Stream<List<_i11.BleService>>>.value(
              _i3.Stream<List<_i11.BleService>>.empty(),
            ),
            returnValueForMissingStub:
                _i3.Future<_i3.Stream<List<_i11.BleService>>>.value(
                  _i3.Stream<List<_i11.BleService>>.empty(),
                ),
          )
          as _i3.Future<_i3.Stream<List<_i11.BleService>>>);

  @override
  _i3.Future<void> disconnect(String? deviceAddress) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [deviceAddress]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i10.BleConnectionState> getCurrentConnectionState(
    String? deviceAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentConnectionState, [deviceAddress]),
            returnValue: _i3.Future<_i10.BleConnectionState>.value(
              _i10.BleConnectionState.connected,
            ),
            returnValueForMissingStub:
                _i3.Future<_i10.BleConnectionState>.value(
                  _i10.BleConnectionState.connected,
                ),
          )
          as _i3.Future<_i10.BleConnectionState>);
}
