const admin = require('../config/adminInit.cjs');
const crypto = require('crypto');
const { sendNotification } = require('./sendNotification.cjs');

/**
 * @brief Updates the battery level and salt level of a device in a Firestore document.
 *
 * This function expects a POST request containing the device ID of the Brine device and
 * updated battery and salt level readings. The request is validated using an HMAC signature
 * provided in the headers. The PSK for the device is retrieved from Firestore for HMAC verification.
 *
 * The function calculates the salt level as a percentage based on the device's salt distance measurement
 * and the total height of the appliance. If either the battery level or calculated salt level percentage
 * is below 5%, a push notification is triggered.
 *
 * Request headers:
 * - X-Device-ID: The unique identifier of the device.
 * - X-HMAC-Signature: The HMAC signature of the request payload, generated by the device.
 *
 * Request body:
 * - device_id (string): The unique identifier of the device.
 * - battery_level (number): The updated battery level (between 0 and 1) of the device.
 * - salt_distance (number): The distance measured between the Brine device and the salt level (millimeters).
 */
async function updateDeviceLevels(req, res) {
    try {
        // Extract headers and request body
        const deviceId = req.headers['x-device-id'];
        const providedHmac = req.headers['x-hmac-signature'];
        const payload = JSON.stringify(req.body);

        if (!deviceId || !providedHmac) {
            res.status(400).send('Missing X-Device-ID or X-HMAC-Signature headers.');
            return;
        }

        // Retrieve the PSK and appliance height from Firestore
        const deviceDoc = await admin.firestore().collection('devices').doc(deviceId).get();
        if (!deviceDoc.exists) {
            res.status(404).send('Device not found.');
            return;
        }

        const deviceData = deviceDoc.data();
        const psk = deviceData.psk;
        const applianceHeight = deviceData.appliance_height;

        if (!psk) {
            res.status(500).send('PSK not found for the device.');
            return;
        }

        if (!applianceHeight || applianceHeight <= 0) {
            res.status(500).send('Appliance height is missing or invalid.');
            return;
        }

        // Compute the expected HMAC using the retrieved PSK
        const hmac = crypto.createHmac('sha256', psk).update(payload).digest('hex');

        // Compare the provided HMAC with the expected HMAC
        if (providedHmac !== hmac) {
            res.status(403).send('Invalid HMAC signature.');
            return;
        }

        // Get the parameters from the request body
        const { battery_level: batteryLevel, salt_distance: saltDistance } = req.body;

        // Get the current timestamp, which will be used as the last updated time
        const lastUpdated = new Date().toISOString();

        // Validate the input data
        if (!deviceId || typeof batteryLevel === 'undefined' || typeof saltDistance === 'undefined') {
            res.status(400).send('Device ID, battery level, and salt distance are required.');
            return;
        }

        // Calculate salt level percentage
        const saltLevelPercent = ((1 - (saltDistance / applianceHeight)) * 100).toFixed(2);

        // Update the Firestore document
        await admin.firestore().collection('devices').doc(deviceId).update({
            'battery_level': batteryLevel,
            'salt_distance': saltDistance,
            'last_updated': lastUpdated,
        });

        console.log(`Device ${deviceId} levels updated: Battery=${batteryLevel}, Salt Level=${saltLevelPercent}%`);

        // Trigger Push Notification if Battery is below 5% or Salt Level is below 5%
        // TODO: Make the threshold values configurable by the user
        if (batteryLevel < 0.05 || saltLevelPercent < 5) {
            console.log(`Device ${deviceId} has low levels. Fetching user details for notifications...`);

            // Find the user who owns this device
            const usersQuery = await admin.firestore()
                .collection('users')
                .where('devices', 'array-contains', deviceId)
                .get();

            // Check if the user exists. It should always exist, but just in case...
            if (!usersQuery.empty) {
                usersQuery.forEach(async (userDoc) => {
                    const userData = userDoc.data();

                    // Get the user's FCM tokens
                    const fcmTokens = userData.fcm_tokens || [];

                    if (fcmTokens.length > 0) {
                        const notificationTitle = "Low Device Levels Alert";
                        let notificationBody = `Your Brine device (${deviceId}) has `;

                        if (batteryLevel < 0.05 && saltLevelPercent < 5) {
                            notificationBody += "low battery and salt levels.";
                        } else if (batteryLevel < 0.05) {
                            notificationBody += "a low battery level.";
                        } else {
                            notificationBody += "a low salt level.";
                        }

                        // Send push notification
                        await sendNotification(fcmTokens, notificationTitle, notificationBody);
                    } else {
                        console.warn(`No FCM tokens found for user ${userDoc.id}. No notification sent.`);
                    }
                });
            } else {
                console.warn(`No user found for device ${deviceId}.`);
            }
        }

        // Respond to the request
        res.status(200).send('Device levels updated successfully.');
    } catch (error) {
        console.error('Error updating device levels:', error);
        res.status(500).send('An error occurred while updating the device levels.');
    }
}

// Export the function to make it available for import
module.exports = { updateDeviceLevels };