const admin = require('../config/adminInit.cjs');
const crypto = require('crypto');

/**
 * @brief Updates the battery level and salt level of a device in a Firestore document.
 *
 * This function expects a POST request containing the device ID of the Brine device and
 * updated battery and salt level readings. The request is validated using an HMAC signature
 * provided in the headers. The PSK for the device is retrieved from Firestore for HMAC verification.
 *
 * Request headers:
 * - X-Device-ID: The unique identifier of the device.
 * - X-HMAC-Signature: The HMAC signature of the request payload, generated by the device.
 *
 * Request body:
 * - device_id (string): The unique identifier of the device.
 * - battery_level (number): The updated battery level (between 0 and 1) of the device.
 * - salt_distance (number): The distance measured between the Brine device and the salt level (millimeters).
 */
async function updateDeviceLevels(req, res) {
    try {
        // Extract headers and request body
        const deviceId = req.headers['x-device-id'];
        const providedHmac = req.headers['x-hmac-signature'];
        const payload = JSON.stringify(req.body);

        if (!deviceId || !providedHmac) {
            res.status(400).send('Missing X-Device-ID or X-HMAC-Signature headers.');
            return;
        }

        // Retrieve the PSK from Firestore
        const deviceDoc = await admin.firestore().collection('devices').doc(deviceId).get();
        if (!deviceDoc.exists) {
            res.status(404).send('Device not found.');
            return;
        }

        const psk = deviceDoc.data().psk;
        if (!psk) {
            res.status(500).send('PSK not found for the device.');
            return;
        }

        // Compute the expected HMAC using the retrieved PSK
        const hmac = crypto.createHmac('sha256', psk).update(payload).digest('hex');

        // Compare the provided HMAC with the expected HMAC
        if (providedHmac !== hmac) {
            res.status(403).send('Invalid HMAC signature.');
            return;
        }

        // Get the parameters from the request body
        const { battery_level: batteryLevel, salt_distance: saltLevel } = req.body;

        // Get the current timestamp, which will be used as the last updated time
        const lastUpdated = new Date().toISOString();

        // Validate the input data
        if (!deviceId || typeof batteryLevel === 'undefined' || typeof saltLevel === 'undefined') {
            res.status(400).send('Device ID, battery level, and salt level are required.');
            return;
        }

        // Update the Firestore document
        await admin.firestore().collection('devices').doc(deviceId).update({
            'battery_level': batteryLevel,
            'salt_distance': saltLevel,
            'last_updated': lastUpdated,
        });

        res.status(200).send('Device levels updated successfully.');
    } catch (error) {
        console.error('Error updating device levels:', error);
        res.status(500).send('An error occurred while updating the device levels.');
    }
}


// Export the function to make it available for import
module.exports = { updateDeviceLevels };